# Compiler and flags
CC = gcc
CFLAGS = -Wall -pthread
TARGET = LogAnalyzer

# Source files
SRCS = 210104004060_main.c buffer.c
OBJS = $(SRCS:.c=.o)

# Default target
all: $(TARGET)

# Build the target executable
$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

# Compile source files into object files
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Clean up build files
clean:
	rm -f $(OBJS) $(TARGET)
